apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mariadb-operator
build:
  artifacts:
    - image: mariadb-operator
      docker:
        dockerfile: Dockerfile
        buildArgs:
          TARGETOS: linux
          TARGETARCH: amd64
      platforms:
        - linux/amd64
    - image: mariadb-test-client
      context: test/client
      docker:
        dockerfile: Dockerfile
      platforms:
        - linux/amd64
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha

# Default deployment: replication setup (1 primary, 2 replicas)
deploy:
  helm:
    hooks:
      before:
        - host:
            command:
              - sh
              - -c
              - |
                # Create mariadb namespace if it doesn't exist
                kubectl create namespace mariadb --dry-run=client -o yaml | kubectl apply -f -
                # Create password secrets in mariadb namespace
                kubectl create secret generic mariadb \
                  --from-literal=root-password=mariadb-root-password \
                  --from-literal=app-password=mariadb-app-password \
                  --namespace=mariadb \
                  --dry-run=client -o yaml | kubectl apply -f -

manifests:
  helm:
    releases:
      - name: mariadb-operator-crds
        chartPath: deploy/charts/mariadb-operator-crds
        namespace: mariadb-system
        createNamespace: true
        upgradeOnChange: true
        wait: true
        version: 25.10.2
      - name: mariadb-operator
        chartPath: deploy/charts/mariadb-operator
        namespace: mariadb-system
        createNamespace: true
        upgradeOnChange: true
        wait: true
        setValueTemplates:
          image.repository: mariadb-operator
          image.tag: "{{.IMAGE_TAG}}"
          image.pullPolicy: IfNotPresent
        setValues:
          webhook.enabled: false
          certController.enabled: false
          logLevel: DEBUG
          ha.enabled: false
        version: 25.10.2
      - name: mariadb-cluster
        chartPath: deploy/charts/mariadb-cluster
        namespace: mariadb
        upgradeOnChange: true
        wait: true
        setValues:
          mariadb.replicas: 3
          mariadb.galera.enabled: false
          mariadb.replication.enabled: true
          mariadb.storage.size: 2Gi
          mariadb.rootPasswordSecretKeyRef.name: mariadb
          mariadb.rootPasswordSecretKeyRef.key: root-password
          # Create test database automatically via Database CR
          databases:
            - name: test
              characterSet: utf8mb4
              collate: utf8mb4_unicode_ci
          # Create app user without SUPER privilege for realistic testing
          users:
            - name: appuser
              passwordSecretKeyRef:
                name: mariadb
                key: app-password
              maxUserConnections: 100
          grants:
            - name: appuser-test-grant
              database: test
              table: "*"
              username: appuser
              privileges:
                - SELECT
                - INSERT
                - UPDATE
                - DELETE
                - CREATE
                - DROP
                - INDEX
                - ALTER
          # Note: Replication config would need additional CRs
          # See examples/manifests/mariadb_replication.yaml
        version: 25.10.2
      # Deploy Istio Gateway (deployment + Gateway CR + VirtualService)
      - name: mariadb-gateway
        chartPath: deploy/charts/mariadb-gateway
        namespace: mariadb
        upgradeOnChange: true
        wait: true
        setValues:
          clusterName: mariadb-cluster
          gateway.name: mariadb-gateway
          gateway.namespace: mariadb
          gateway.port: 3306
          gateway.selector.istio: mariadb-ingress
          virtualService.name: mariadb-vs
          virtualService.backendService: mariadb-cluster-primary
          virtualService.backendPort: 3306
          # Gateway deployment configuration (values for subchart)
          istio-gateway.labels.app: mariadb-gateway
          istio-gateway.labels.istio: mariadb-ingress
          istio-gateway.service.type: ClusterIP
          istio-gateway.resources.requests.cpu: 100m
          istio-gateway.resources.requests.memory: 128Mi
          istio-gateway.resources.limits.cpu: 500m
          istio-gateway.resources.limits.memory: 512Mi
      - name: mariadb-test-client
        chartPath: test/client/chart
        namespace: mariadb
        upgradeOnChange: true
        wait: false
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED_mariadb_test_client}}"
        setValues:
          imagePullPolicy: IfNotPresent
          # Connect through dedicated Gateway (Gateway/VirtualService created separately)
          mariadb.host: mariadb-gateway.mariadb.svc.cluster.local
          mariadb.port: 3306
          mariadb.user: appuser
          mariadb.passwordSecret.name: mariadb
          mariadb.passwordSecret.key: app-password
          mariadb.database: test
          client.writeInterval: 0.5

profiles:
  # Profile for installing Istio control plane (base + istiod)
  - name: istio
    manifests:
      helm:
        releases:
          - name: istio-base
            remoteChart: base
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
            upgradeOnChange: true
            wait: true
            version: 1.16.7
          - name: istiod
            remoteChart: istiod
            repo: https://istio-release.storage.googleapis.com/charts
            namespace: istio-system
            createNamespace: true
            upgradeOnChange: true
            wait: true
            version: 1.16.7
